version: '3.8'

services:
  mcp-filesystem:
    image: python:3.11-slim
    container_name: mcp-filesystem
    working_dir: /app
    volumes:
      - ./data:/app/data
    command: >
      sh -c "
        curl -sSL https://raw.githubusercontent.com/apisani1/mcp-python-bootstrap/main/scripts/universal-bootstrap.sh |
        sh -s -- mcp-server-filesystem --root /app/data
      "
    environment:
      - MCP_BOOTSTRAP_CACHE_DIR=/tmp/mcp-cache
    restart: unless-stopped
    networks:
      - mcp-network

  mcp-database:
    image: python:3.11-slim
    container_name: mcp-database
    working_dir: /app
    volumes:
      - ./db:/app/db
    command: >
      sh -c "
        curl -sSL https://raw.githubusercontent.com/apisani1/mcp-python-bootstrap/main/scripts/universal-bootstrap.sh |
        sh -s -- mcp-server-sqlite --db-path /app/db/app.db
      "
    environment:
      - MCP_BOOTSTRAP_CACHE_DIR=/tmp/mcp-cache
    restart: unless-stopped
    networks:
      - mcp-network

  mcp-web:
    image: python:3.11-alpine
    container_name: mcp-web
    ports:
      - "8080:8080"
    command: >
      sh -c "
        apk add --no-cache curl &&
        curl -sSL https://raw.githubusercontent.com/apisani1/mcp-python-bootstrap/main/scripts/universal-bootstrap.sh |
        sh -s -- mcp-server-web --port 8080 --host 0.0.0.0
      "
    environment:
      - MCP_BOOTSTRAP_CACHE_DIR=/tmp/mcp-cache
    restart: unless-stopped
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge

volumes:
  data:
  db: